# Generated by Django 5.2.3 on 2025-06-22 11:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnlagenListe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Listenname')),
                ('beschreibung', models.TextField(blank=True, verbose_name='Beschreibung')),
                ('erstellt_am', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
                ('aktualisiert_am', models.DateTimeField(auto_now=True, verbose_name='Aktualisiert am')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anlagen_listen', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Anlagen-Liste',
                'verbose_name_plural': 'Anlagen-Listen',
                'ordering': ['-aktualisiert_am'],
            },
        ),
        migrations.CreateModel(
            name='GespeicherteAnlage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anlagen_id', models.CharField(max_length=100, verbose_name='MaStR Anlagen-ID')),
                ('anlagenname', models.CharField(max_length=500, verbose_name='Anlagenname')),
                ('energietraeger', models.CharField(max_length=100, verbose_name='Energieträger')),
                ('leistung', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Leistung (kW)')),
                ('bundesland', models.CharField(max_length=100, verbose_name='Bundesland')),
                ('ort', models.CharField(max_length=200, verbose_name='Ort')),
                ('plz', models.CharField(max_length=10, verbose_name='PLZ')),
                ('status', models.CharField(max_length=100, verbose_name='Betriebs-Status')),
                ('technologie', models.CharField(blank=True, max_length=200, verbose_name='Technologie')),
                ('betreiber', models.CharField(blank=True, max_length=500, verbose_name='Betreiber')),
                ('inbetriebnahme', models.DateField(blank=True, null=True, verbose_name='Inbetriebnahme')),
                ('hinzugefuegt_am', models.DateTimeField(auto_now_add=True, verbose_name='Hinzugefügt am')),
                ('notizen', models.TextField(blank=True, verbose_name='Notizen')),
                ('liste', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anlagen', to='dashboard.anlagenliste')),
            ],
            options={
                'verbose_name': 'Gespeicherte Anlage',
                'verbose_name_plural': 'Gespeicherte Anlagen',
                'ordering': ['-hinzugefuegt_am'],
                'unique_together': {('liste', 'anlagen_id')},
            },
        ),
    ]
