# Generated by Django 5.2.3 on 2025-06-22 13:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_anlagenliste_gespeicherteanlage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnlagenBetreiber',
            fields=[
                ('betreibernummer', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('strasse', models.CharField(blank=True, max_length=255, null=True)),
                ('plz', models.CharField(blank=True, max_length=10, null=True)),
                ('ort', models.CharField(blank=True, max_length=255, null=True)),
                ('bundesland', models.CharField(blank=True, max_length=100, null=True)),
                ('telefon', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('anzahl_anlagen', models.IntegerField(default=0)),
                ('gesamtleistung', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('hauptenergietraeger', models.CharField(blank=True, max_length=100, null=True)),
                ('erstellt_am', models.DateTimeField(auto_now_add=True)),
                ('aktualisiert_am', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Anlagenbetreiber',
                'verbose_name_plural': 'Anlagenbetreiber',
                'ordering': ['-anzahl_anlagen', 'name'],
            },
        ),
        migrations.CreateModel(
            name='UserAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(blank=True, max_length=100, null=True)),
                ('event_type', models.CharField(max_length=50)),
                ('event_name', models.CharField(max_length=100)),
                ('page_url', models.CharField(blank=True, max_length=500, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('additional_data', models.JSONField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Nutzungsanalyse',
                'verbose_name_plural': 'Nutzungsanalysen',
                'ordering': ['-timestamp'],
            },
        ),
    ]
