# Generated by Django 5.2.3 on 2025-06-22 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_anlagenbetreiber_useranalytics'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AnlagenBetreiber',
        ),
        migrations.DeleteModel(
            name='UserAnalytics',
        ),
    ]
