# Generated by Django 5.2.3 on 2025-06-22 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_delete_anlagenbetreiber_delete_useranalytics'),
    ]

    operations = [
        migrations.AddField(
            model_name='gespeicherteanlage',
            name='anlagenstatus',
            field=models.CharField(choices=[('neu', 'Neu'), ('kontaktiert', 'Kontaktiert'), ('in_bearbeitung', 'In Bearbeitung'), ('angebot_versendet', 'Angebot versendet'), ('verhandlungen', 'In Verhandlungen'), ('abgeschlossen', 'Abgeschlossen'), ('abgelehnt', 'Abgelehnt'), ('archiviert', 'Archiviert')], default='neu', max_length=20, verbose_name='Anlagenstatus'),
        ),
        migrations.AddField(
            model_name='gespeicherteanlage',
            name='benutzer_notizen',
            field=models.TextField(blank=True, verbose_name='Benutzer-Notizen'),
        ),
        migrations.AddField(
            model_name='gespeicherteanlage',
            name='letzte_bearbeitung',
            field=models.DateTimeField(auto_now=True, verbose_name='Letzte Bearbeitung'),
        ),
        migrations.AddField(
            model_name='gespeicherteanlage',
            name='prioritaet',
            field=models.CharField(choices=[('niedrig', 'Niedrig'), ('mittel', 'Mittel'), ('hoch', 'Hoch'), ('kritisch', 'Kritisch')], default='mittel', max_length=20, verbose_name='Priorität'),
        ),
    ]
