# Generated by Django 5.2.3 on 2025-06-22 17:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_gespeicherteanlage_anlagenstatus_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnlagenFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mastr_anlagen_id', models.CharField(blank=True, max_length=100, verbose_name='MaStR Anlagen-ID')),
                ('feedback_typ', models.CharField(choices=[('daten_fehler', 'Datenfehler'), ('veraltete_daten', 'Veraltete Daten'), ('fehlende_daten', 'Fehlende Daten'), ('falsche_zuordnung', 'Falsche Zuordnung'), ('sonstiges', 'Sonstiges')], max_length=20, verbose_name='Feedback-Typ')),
                ('titel', models.CharField(max_length=200, verbose_name='Titel')),
                ('beschreibung', models.TextField(verbose_name='Beschreibung des Problems')),
                ('vorgeschlagene_korrektur', models.TextField(blank=True, verbose_name='Vorgeschlagene Korrektur')),
                ('status', models.CharField(choices=[('neu', 'Neu'), ('in_bearbeitung', 'In Bearbeitung'), ('geloest', 'Gelöst'), ('abgelehnt', 'Abgelehnt')], default='neu', max_length=20, verbose_name='Status')),
                ('admin_antwort', models.TextField(blank=True, verbose_name='Admin-Antwort')),
                ('erstellt_am', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
                ('aktualisiert_am', models.DateTimeField(auto_now=True, verbose_name='Aktualisiert am')),
                ('geloest_am', models.DateTimeField(blank=True, null=True, verbose_name='Gelöst am')),
                ('admin_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_feedback', to=settings.AUTH_USER_MODEL)),
                ('gespeicherte_anlage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='dashboard.gespeicherteanlage')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anlagen_feedback', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Anlagen-Feedback',
                'verbose_name_plural': 'Anlagen-Feedback',
                'ordering': ['-erstellt_am'],
            },
        ),
    ]
