# Generated by Django 5.2.4 on 2025-07-05 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Stadt'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='company_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Firmenname'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Land'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefonnummer'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='postal_code',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Postleitzahl'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='street_address',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Straße & Hausnummer'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='tax_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Steuernummer/USt-IdNr.'),
        ),
    ]
