# Generated by Django 5.2.3 on 2025-06-22 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='requestlog',
            options={'verbose_name': 'Anfragen-Log', 'verbose_name_plural': 'Anfragen-Logs'},
        ),
    ]
