# Generated by Django 5.2.3 on 2025-07-05 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0002_alter_requestlog_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="usersubscription",
            name="is_trial",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="usersubscription",
            name="trial_end_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
